name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload site contents
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./   # bundle everything in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
